// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOE9jY66eaOS5dlsA7lmBfNVdj_K2whkU',
    appId: '1:665674591247:web:29a523aa5572d261cdc77a',
    messagingSenderId: '665674591247',
    projectId: 'prct-ba353',
    authDomain: 'prct-ba353.firebaseapp.com',
    storageBucket: 'prct-ba353.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGnxvOhnPfdw4Jaf0H6dBfac7aJ1HffFI',
    appId: '1:575253185128:web:39a74f3dc2a762c6a671dd',
    messagingSenderId: '575253185128',
    projectId: 'watertempok',
    authDomain: 'watertempok.firebaseapp.com',
    databaseURL: 'https://watertempok-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'watertempok.firebasestorage.app',
    measurementId: 'G-3LWB4HGHN0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASK6rkDTxKXji60vjX2Lc4DwK6HBxfSHQ',
    appId: '1:575253185128:ios:19ae6b1151a4ae97a671dd',
    messagingSenderId: '575253185128',
    projectId: 'watertempok',
    databaseURL: 'https://watertempok-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'watertempok.firebasestorage.app',
    iosBundleId: 'com.example.iotWaterLevelTrack',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASK6rkDTxKXji60vjX2Lc4DwK6HBxfSHQ',
    appId: '1:575253185128:ios:19ae6b1151a4ae97a671dd',
    messagingSenderId: '575253185128',
    projectId: 'watertempok',
    databaseURL: 'https://watertempok-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'watertempok.firebasestorage.app',
    iosBundleId: 'com.example.iotWaterLevelTrack',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLVCfmoBQ5KNtSRE2abnQoVtFRM32hauA',
    appId: '1:575253185128:android:9db4e1a0c0193fffa671dd',
    messagingSenderId: '575253185128',
    projectId: 'watertempok',
    databaseURL: 'https://watertempok-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'watertempok.firebasestorage.app',
  );

}